### ISSUE TITLE
Page took too long to respond 

### ISSUE THREAD

**Issue by harshlancer** [AmitKKhanchandani/React-Assignment-pgs#1]
![image](https://user-images.githubusercontent.com/91771779/211392085-68c1e64f-2fe9-4e29-b5a9-39e140e20b72.png)
Login page and other pages took too long to open

**Comment by AmitKKhanchandani** [comment]
The content are hosted at github site.

try opening this link https://amitkkhanchandani.github.io/React-Assignment-pgs/

**Comment by AmitKKhanchandani** [comment]
closing this issue as the project is loading as expected

![image](https://user-images.githubusercontent.com/11069057/216546414-73733573-d152-4ea5-9d61-e4bc85fe97a8.png)
